CREATE TABLE [ClassRooms]
(
 [Id] INT PRIMARY KEY IDENTITY NOT NULL,
 [Name] NVARCHAR (30) NOT NULL,
 [Capacity] TINYINT DEFAULT 0 NOT NULL,
 [QuantityOfBoards] TINYINT DEFAULT 0 NOT NULL,
 [QuantityOfPrinters] TINYINT DEFAULT 0 NOT NULL,
 [QuantityOfTables] TINYINT DEFAULT 0 NOT NULL,
 [QuantityOfLaptops] TINYINT DEFAULT 0 NOT NULL,
 [IsLocked]   BIT DEFAULT 1 NOT NULL

)