CREATE TABLE [Feedback]
(
 [Id]  INT PRIMARY KEY  IDENTITY NOT NULL,
 [FirstName] NVARCHAR(50) NOT NULL,
 [LastName] NVARCHAR(50) NOT NULL,
 [Email] NVARCHAR(256) NOT NULL,
 [Text] NVARCHAR(3000) NOT NULL
)
GO
