CREATE TABLE [Participant]
(
 [Id]  INT PRIMARY KEY IDENTITY,
 [Name] NVARCHAR(60	) NOT NULL,
 [EventId] INT NOT NULL
)
GO

ALTER TABLE [Participant] ADD CONSTRAINT FK_Participant_Event FOREIGN KEY (EventId) 
 REFERENCES [Event](Id)
GO