CREATE TABLE [Event]
(
 [Id] INT PRIMARY KEY IDENTITY NOT NULL,
 [Title] NVARCHAR(100) NOT NULL,
 [AuthorId] NVARCHAR(128) NOT NULL,
 [ClassRoomId] INT NOT NULL,
 [Organizer] NVARCHAR (50) NULL,
 [BeginingDate] DATETIME NOT NULL,
 [EndingDate] DATETIME NOT NULL,
 [Description] NVARCHAR(200) NULL,
 [IsPublic] BIT DEFAULT 1,
 [IsAuthorShown] BIT DEFAULT 1
)
GO


ALTER TABLE [Event] ADD CONSTRAINT FK_Event_User FOREIGN KEY (AuthorID)  REFERENCES [AspNetUsers](Id)
GO
ALTER TABLE [Event] ADD CONSTRAINT FK_Event_Room FOREIGN KEY (ClassRoomId)  REFERENCES [ClassRoom](Id)
GO