//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SofthemeClassBooking.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SofthemeClassBooking.Localization.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список пользователей.
        /// </summary>
        public static string AccountUserList {
            get {
                return ResourceManager.GetString("AccountUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string ButtonCancelation {
            get {
                return ResourceManager.GetString("ButtonCancelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать.
        /// </summary>
        public static string ButtonCreate {
            get {
                return ResourceManager.GetString("ButtonCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string ButtonEdit {
            get {
                return ResourceManager.GetString("ButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string ButtonLogOut {
            get {
                return ResourceManager.GetString("ButtonLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить.
        /// </summary>
        public static string ButtonSend {
            get {
                return ResourceManager.GetString("ButtonSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите отменить событие?.
        /// </summary>
        public static string DialogCancelEventTitle {
            get {
                return ResourceManager.GetString("DialogCancelEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все события, запланированные в данной аудитории, будут отменены..
        /// </summary>
        public static string DialogCancelRoomBody {
            get {
                return ResourceManager.GetString("DialogCancelRoomBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверенны,что хотите закрыть эту аудиторию?.
        /// </summary>
        public static string DialogCancelRoomTitle {
            get {
                return ResourceManager.GetString("DialogCancelRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        public static string DialogNo {
            get {
                return ResourceManager.GetString("DialogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ок.
        /// </summary>
        public static string DialogOk {
            get {
                return ResourceManager.GetString("DialogOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        public static string DialogYes {
            get {
                return ResourceManager.GetString("DialogYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка загрузки диалогового окна.
        /// </summary>
        public static string ErrorDialogWindow {
            get {
                return ResourceManager.GetString("ErrorDialogWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный адрес электронной почты.
        /// </summary>
        public static string ErrorEmail {
            get {
                return ResourceManager.GetString("ErrorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не может быть пустым.
        /// </summary>
        public static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже принимаете участие в событии.
        /// </summary>
        public static string ErrorEventAlreadyEnrolledPlaceholder {
            get {
                return ResourceManager.GetString("ErrorEventAlreadyEnrolledPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудитория полностью занята.
        /// </summary>
        public static string ErrorEventParticipantReachedMaximumPlaceholder {
            get {
                return ResourceManager.GetString("ErrorEventParticipantReachedMaximumPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие уже свершилось.
        /// </summary>
        public static string ErrorEventPassedPlaceholder {
            get {
                return ResourceManager.GetString("ErrorEventPassedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле слишком длинное.
        /// </summary>
        public static string ErrorFieldTooLong {
            get {
                return ResourceManager.GetString("ErrorFieldTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при выполнении операции. Попробуйте позже.
        /// </summary>
        public static string ErrorGeneralException {
            get {
                return ResourceManager.GetString("ErrorGeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный адрес электронной почты.
        /// </summary>
        public static string ErrorIncorrectEmail {
            get {
                return ResourceManager.GetString("ErrorIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введены неверные данные..
        /// </summary>
        public static string ErrorModelValidation {
            get {
                return ResourceManager.GetString("ErrorModelValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор или организатор не указаны.
        /// </summary>
        public static string ErrorNoAuthor {
            get {
                return ResourceManager.GetString("ErrorNoAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание не указано.
        /// </summary>
        public static string ErrorNoDescription {
            get {
                return ResourceManager.GetString("ErrorNoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это поле обязательно для заполения.
        /// </summary>
        public static string ErrorRequiredField {
            get {
                return ResourceManager.GetString("ErrorRequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В аудитории недостаточно места для проведения события..
        /// </summary>
        public static string ErrorRoomCapacityLessOne {
            get {
                return ResourceManager.GetString("ErrorRoomCapacityLessOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта аудитория занята на выбранное время. Выберите, пожалуйста, другое.
        /// </summary>
        public static string ErrorRoomIsBusy {
            get {
                return ResourceManager.GetString("ErrorRoomIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительная информация.
        /// </summary>
        public static string EventAdditionalInfoPlaceholder {
            get {
                return ResourceManager.GetString("EventAdditionalInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарезервировать аудиторию.
        /// </summary>
        public static string EventBookClassRoom {
            get {
                return ResourceManager.GetString("EventBookClassRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возможность регистрации отключена.
        /// </summary>
        public static string EventOffRegistration {
            get {
                return ResourceManager.GetString("EventOffRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединиться.
        /// </summary>
        public static string EventParticipantJoin {
            get {
                return ResourceManager.GetString("EventParticipantJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите e-mail чтобы присоединиться.
        /// </summary>
        public static string EventParticipantJoinPlaceholder {
            get {
                return ResourceManager.GetString("EventParticipantJoinPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приняли участие.
        /// </summary>
        public static string EventParticipantsTookPart {
            get {
                return ResourceManager.GetString("EventParticipantsTookPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планируют принять участие .
        /// </summary>
        public static string EventPlanningTakePart {
            get {
                return ResourceManager.GetString("EventPlanningTakePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приватно.
        /// </summary>
        public static string EventPrivate {
            get {
                return ResourceManager.GetString("EventPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публично.
        /// </summary>
        public static string EventPublic {
            get {
                return ResourceManager.GetString("EventPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрирование участники.
        /// </summary>
        public static string EventRegistered {
            get {
                return ResourceManager.GetString("EventRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация желающих.
        /// </summary>
        public static string EventRegisterParticipants {
            get {
                return ResourceManager.GetString("EventRegisterParticipants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание аудитории.
        /// </summary>
        public static string EventRoomSchedule {
            get {
                return ResourceManager.GetString("EventRoomSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указать организатора.
        /// </summary>
        public static string EventSetOrganizerPlaceholder {
            get {
                return ResourceManager.GetString("EventSetOrganizerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать автора.
        /// </summary>
        public static string EventShowAuthor {
            get {
                return ResourceManager.GetString("EventShowAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string EventTitlePlaceholder {
            get {
                return ResourceManager.GetString("EventTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приняли участие.
        /// </summary>
        public static string EventTookPart {
            get {
                return ResourceManager.GetString("EventTookPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес электронной почты.
        /// </summary>
        public static string FeedbackEmailPlaceholder {
            get {
                return ResourceManager.GetString("FeedbackEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string FeedbackLastnamePlaceholder {
            get {
                return ResourceManager.GetString("FeedbackLastnamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные введены неверно. Попробуйте еще раз..
        /// </summary>
        public static string FeedBackModelError {
            get {
                return ResourceManager.GetString("FeedBackModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FeedbackNamePlaceholder {
            get {
                return ResourceManager.GetString("FeedbackNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишите, если у вас есть идеи, предложения, замечания или вопросы.
        /// </summary>
        public static string FeedbackNoteToUser {
            get {
                return ResourceManager.GetString("FeedbackNoteToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо. Ваше сообщение отправлено администратору.
        /// </summary>
        public static string FeedBackSuccess {
            get {
                return ResourceManager.GetString("FeedBackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Написать сообщение.
        /// </summary>
        public static string FeedbackWriteMessage {
            get {
                return ResourceManager.GetString("FeedbackWriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше событие было успешно добавлено в рассписание.
        /// </summary>
        public static string InfoEventAddedSuccess {
            get {
                return ResourceManager.GetString("InfoEventAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Событие было успешно изменено.
        /// </summary>
        public static string InfoEventChangedSuccess {
            get {
                return ResourceManager.GetString("InfoEventChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно записались на событие.
        /// </summary>
        public static string InfoParticipantAddedSuccess {
            get {
                return ResourceManager.GetString("InfoParticipantAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратная связь.
        /// </summary>
        public static string LayoutNavFeedback {
            get {
                return ResourceManager.GetString("LayoutNavFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string LayoutNavLogIn {
            get {
                return ResourceManager.GetString("LayoutNavLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание.
        /// </summary>
        public static string LayoutNavSchedule {
            get {
                return ResourceManager.GetString("LayoutNavSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string LayoutNavUsers {
            get {
                return ResourceManager.GetString("LayoutNavUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка карты.
        /// </summary>
        public static string LoadingMapSection {
            get {
                return ResourceManager.GetString("LoadingMapSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка плана этажа.
        /// </summary>
        public static string LoadingPlanSection {
            get {
                return ResourceManager.GetString("LoadingPlanSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка таблицы расписания....
        /// </summary>
        public static string LoadingRoomEventSection {
            get {
                return ResourceManager.GetString("LoadingRoomEventSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to г. Киев, ул. Деловая, 5А.
        /// </summary>
        public static string MapAddress {
            get {
                return ResourceManager.GetString("MapAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to или.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница аудитории.
        /// </summary>
        public static string PageRoom {
            get {
                return ResourceManager.GetString("PageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to человек.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расписание.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этаж.
        /// </summary>
        public static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберете аудиторию на этаже.
        /// </summary>
        public static string StageSelect {
            get {
                return ResourceManager.GetString("StageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество активных событий.
        /// </summary>
        public static string UserActiveEventCount {
            get {
                return ResourceManager.GetString("UserActiveEventCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно изменен.
        /// </summary>
        public static string UserChangedPasswordSuccess {
            get {
                return ResourceManager.GetString("UserChangedPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        public static string UserChangePassword {
            get {
                return ResourceManager.GetString("UserChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Когда.
        /// </summary>
        public static string When {
            get {
                return ResourceManager.GetString("When", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Где.
        /// </summary>
        public static string Where {
            get {
                return ResourceManager.GetString("Where", resourceCulture);
            }
        }
    }
}
